### ISSUE TITLE
Stremio freezing and unresponsive sometimes

### ISSUE THREAD

**Issue by buckbidoof** [Stremio/stremio-linux-shell#68]
### Installation type

Flatpak (.flatpak)

### Platform

CachyOS

### GPU

AMD

### Describe the bug

This bug has been happening since I updated to v1.0.0
Every now and then when I interact with the video player, or doing something on the side (alt-tabbing), Stremio freezes and becomes unresponsive. Whatever was last displayed on Stremio is shown but frozen, and if a video was playing as it happened, you can still hear the audio like it's still playing, just with Stremio frozen and I'm unable to interact with it at all.
Not sure what the cause is but I'll attach the output that was shown when I last used it until I was forced to terminate it:
```
(node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(node:4) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
Cannot load libcuda.so.1
2026-06-27T23:44:54.547697Z ERROR stremio_linux_shell::app::webview: Failed to send message: TypeError: undefined is not a function
(node:4) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

(stremio:2): Gdk-WARNING **: 18:44:56.459: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)
2026-06-27T23:44:57.362999Z ERROR stremio_linux_shell::app::ipc: Failed to convert IpcEvent to IpcMessageRequest: Invalid method: mpv-set-gpu-video-processing
2026-06-27T23:44:57.365850Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/request/1_724/ashpd_MsmHcmAefR”. Property change streams will not produce values.

(stremio:2): Gdk-WARNING **: 18:44:58.185: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 18:45:05.996: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:05:34.989: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:05:36.347: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:06:07.839: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:06:08.481: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:06:08.502: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)
2026-06-28T00:06:08.826427Z ERROR stremio_linux_shell::app::ipc: Failed to convert IpcEvent to IpcMessageRequest: Invalid method: mpv-set-gpu-video-processing
2026-06-28T00:06:08.829797Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/request/1_724/ashpd_xPduZHOxcT”. Property change streams will not produce values.

(stremio:2): Gdk-WARNING **: 19:06:09.014: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:06:13.256: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:06:16.515: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:24:49.070: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:26:45.241: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)
2026-06-28T00:29:55.575374Z ERROR stremio_linux_shell::app::ipc: Failed to convert IpcEvent to IpcMessageRequest: Invalid method: mpv-set-gpu-video-processing
2026-06-28T00:29:55.577922Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/request/1_724/ashpd_ihi4f8VkFv”. Property change streams will not produce values.

(stremio:2): Gdk-WARNING **: 19:36:05.090: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:36:06.770: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:57:10.859: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 19:57:10.874: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)
2026-06-28T01:09:49.364640Z ERROR stremio_linux_shell::app::ipc: Failed to convert IpcEvent to IpcMessageRequest: Invalid method: mpv-set-gpu-video-processing
2026-06-28T01:09:49.367159Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/request/1_724/ashpd_FSbyEFX4VM”. Property change streams will not produce values.

(stremio:2): Gdk-WARNING **: 20:09:50.723: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 20:09:51.194: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 20:09:51.615: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)

(stremio:2): Gdk-WARNING **: 20:09:57.808: vkAcquireNextImageKHR(): A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully. (VK_SUBOPTIMAL_KHR) (1000001003)
Engine invalid piece 19032 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19033 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19034 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19035 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19036 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19037 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19038 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
Engine invalid piece 19039 for 09760b4724856e9d8eba76bfdfd00b079a2b3585
```

This is the output during a watch session I had. The `Engine invalid piece` parts appeared when the program became unresponsive and it happened after I paused the video I was currently watching.

**Comment by adrianjch** [comment]
Same freezing bug exactly as described. Here in CachyOS too but with an NVIDIA GPU

**Comment by OcheOps** [comment]
Confirming this on **Fedora 44 + GNOME/Wayland + AMD (amdgpu)** with the same Flatpak build (`com.stremio.Stremio` v1.0.3 from Flathub). Symptoms match exactly: UI freezes shortly after interacting with a stream, audio continues after the window is closed, and only `pkill -9 -f 'stremio|node.*server.js'` fully stops it.

Log signature is identical to the OP:
```
Cannot load libcuda.so.1
ERROR stremio_linux_shell::app::webview: Failed to send message: TypeError: undefined is not a function
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
```

Additional data from my run:
- mpv VO init also fails (may be related to the freeze):
  ```
  WARN  stremio_linux_shell::app::ipc: Failed to convert IpcEvent to IpcMessageRequest: Invalid method: mpv-set-gpu-video-processing
  WARN  stremio_linux_shell::app::video: Failed to set property vo: Unsupported
  ERROR stremio_linux_shell::app::video::imp: Failed to wait for event: Raw(-13)   # MPV_ERROR_VO_INIT_FAILED
  ```
- One Stremio scope consumed **24 min CPU over 29 min wall time** (systemd accounting), consistent with a tight retry loop while the UI is frozen.
- Tried without success: `flatpak update`, `flatpak override --user com.stremio.Stremio --device=dri --socket=pulseaudio`, wiping `~/.var/app/com.stremio.Stremio/.stremio-server/stremio-cache` and `cache/mesa_shader_cache*`, reboot.
- Workaround for me: https://web.stremio.com works flawlessly against the same account.

Env: `Linux 7.0.14-201.fc44.x86_64`, GNOME on Wayland, no NVIDIA driver present (so the `libcuda.so.1` load attempt should probably be gated on NVIDIA presence).
