### ISSUE TITLE
Unable to launch via menu/destkop shortcut - only runs from command line

### ISSUE THREAD

**Issue by MaciekMaciek87** [Stremio/stremio-linux-shell#102]
### Installation type

Flatpak (.flatpak)

### Version

1.1.2

### Platform

Fedora 44

### Desktop Environment

KDE 6.7.2.

### Windowing System

Wayland

### GPU

AMD Radeon 6600

### Describe the bug

Hello everyone,

Since updating to 1.1.2 I find myself unable to launch the app using KDE's menu shortcut - the icon appears on the taskbar for a few seconds, and then disappears, without the app launching properly. Using "flatpak run com.stremio.Stremio" I am able to  launch the app, but pressing the "X" button in the top right corner of the window closes it completely, and I have to run the same command to launch the app again.  I tried downgrading to V4 using instructions provided here - https://blog.stremio.com/stremio-tech-update-81-stremio-v5-released-for-linux/ - but keep getting error 404. Has the previous build been deleted? I will be grateful for any help. Thank you!

### Logs

(node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(node:4) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
Cannot load libcuda.so.1
2026-07-10T11:59:16.226722Z ERROR stremio_linux_shell::app::webview: Failed to send message: TypeError: undefined is not a function
(node:4) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

**Comment by tymmesyde** [comment]
Hi, do you have any other Stremio apps installed on your system?

**Comment by MaciekMaciek87** [comment]
Hi Tym,

No, only Stremio is installed via Flatpak through KDE Discover - the "flatpak list" command only lists one entry for Stremio, that being com.stremio.Stremio. It does say that the version is 1.0.3. However, when running "flatpak update" it says "nothing to update".  In the "About Stremio" section of the app's hamburger menu the app states that the version is 1.1.2.

**Comment by MaciekMaciek87** [comment]
Adding new logs I was able to get from running flatpak run com.stremio.Stremio:

(node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(node:4) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
Cannot load libcuda.so.1
2026-07-10T17:12:50.282759Z ERROR stremio_linux_shell::app::webview: Failed to send message: TypeError: undefined is not a function
(node:4) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Error: stream ended
    at Socket.onFinished (/app/libexec/stremio/server.js:80165:145)
    at Socket.<anonymous> (node:internal/util:545:20)
    at Socket.onfinish (node:internal/streams/end-of-stream:112:16)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at finish (node:internal/streams/writable:955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
2026-07-10T17:13:04.077787Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Obiekt nie istnieje w ścieżce „/org/freedesktop/portal/desktop/request/1_173/ashpd_KzO7tfcREe”. Property change streams will not produce values.
2026-07-10T17:13:04.077930Z  WARN {}{task_name="org.freedesktop.portal.Request proxy caching"}: zbus::proxy: Failed to populate properties cache via GetAll: org.freedesktop.DBus.Error.UnknownMethod: Obiekt nie istnieje w ścieżce „/org/freedesktop/portal/desktop/request/1_173/ashpd_jbV3wnlE1H”. Property change streams will not produce values.

(stremio:2): Gdk-WARNING **: 19:13:04.082: Use gdk_wayland_toplevel_drop_exported_handle()

thread 'main' (2) panicked at /run/build/stremio/cargo/vendor/ashpd-0.13.11/src/window_identifier/gtk4.rs:181:59:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
